### ISSUE TITLE
Standardise on requirements.txt rather than Pipfile

### ISSUE THREAD

**Issue by sebbASF** [apache/infrastructure-asfquart#10]
Most other Infra Python projects use a requirements.txt file rather than a Pipfile.

**Comment by gstein** [comment]
Ugh. I didn't even know about the Pipfile. I recently added a new requirement to pyproject.toml and missed Pipfile. ... I don't even know what uses Pipfile.

pyproject.toml is the appropriate place to put dependencies, as that's what is used to build the package for upload to PyPI. Note sure if pip can read a .toml

**Comment by Humbedooh** [comment]
Pipfile was used for pytest coverage and only that. I believe this is now covered by the TOML and Poetry, so it should have obsoleted itself by now. I'll verify with Wells.

**Comment by gstein** [comment]
We have decided to standardize on pyproject.toml and the Poetry tool.
